package com.domu.domain;

public enum NotificationType {
    INCIDENT_CREATED,
    INCIDENT_ASSIGNED,
    INCIDENT_STATUS_CHANGED,
    VISIT_AUTHORIZED,
    VISIT_CHECKED_IN,
    PARCEL_RECEIVED,
    PARCEL_COLLECTED,
    CHARGE_PERIOD_CREATED,
    PAYMENT_CONFIRMED,
    TASK_ASSIGNED,
    TASK_COMPLETED,
    POLL_CREATED,
    POLL_CLOSED,
    RESERVATION_CONFIRMED,
    RESERVATION_CANCELLED,
    FORUM_THREAD_CREATED,
    ADMIN_ANNOUNCEMENT,
    MARKET_ITEM_CREATED,
    CHAT_REQUEST_RECEIVED,
    CHAT_REQUEST_ACCEPTED,
    MAINTENANCE_SCHEDULED,
    MAINTENANCE_COMPLETED
}
