/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.1.0/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Javalin web framework
    implementation(libs.javalin)
    
    // Logging
    implementation(libs.slf4j.simple)
    
    // JSON serialization/deserialization
    implementation(libs.jackson.databind)
    implementation(libs.jackson.datatype.jsr310)
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("5.12.1")
            
            dependencies {
                // JUnit dependencies
                implementation(libs.junit.jupiter)
                // Javalin test utilities
                implementation(libs.javalin.testtools)
            }
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    // Define the main class for the application.
    mainClass = "com.domu.App"
}

tasks.named<JavaExec>("run") {
    standardInput = System.`in`
}
