/*
 * This source file was generated by the Gradle 'init' task
 */
package com.domu;

import io.javalin.Javalin;
import io.javalin.testtools.JavalinTest;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    
    @Test
    void testHealthEndpoint() {
        App app = new App();
        Javalin javalinApp = app.createApp();
        
        JavalinTest.test(javalinApp, (server, client) -> {
            var response = client.get("/health");
            assertEquals(200, response.code());
            assertTrue(response.body().string().contains("UP"));
        });
    }
    
    @Test
    void testWelcomeEndpoint() {
        App app = new App();
        Javalin javalinApp = app.createApp();
        
        JavalinTest.test(javalinApp, (server, client) -> {
            var response = client.get("/");
            assertEquals(200, response.code());
            assertTrue(response.body().string().contains("Welcome to Domu Backend API"));
        });
    }
    
    @Test
    void testGetAllUsersEndpoint() {
        App app = new App();
        Javalin javalinApp = app.createApp();
        
        JavalinTest.test(javalinApp, (server, client) -> {
            var response = client.get("/api/v1/users");
            assertEquals(200, response.code());
            String body = response.body().string();
            assertTrue(body.contains("John Doe"));
            assertTrue(body.contains("Jane Smith"));
        });
    }
}
